### ISSUE TITLE
Issues running stack llama example

### ISSUE THREAD

**Issue by vshah505** [lvwerra/trl#313]
When attempting to run the [stack_llama](https://github.com/lvwerra/trl/tree/main/examples/stack_llama/scripts) example, I was able to run the first two steps:

`torchrun --nnodes=1  --nproc_per_node=4 supervised_finetuning.py --model_path=/home/vishal/models/llama_hf --streaming --no_gradient_checkpointing --learning_rate=1e-5 --max_steps=5000 --output_dir ./llama-se`
and

`torchrun --nnodes 1 --nproc_per_node 4 reward_modeling.py --model_name=/home/vishal/stack_llama/llama-se-model`

However, when running the third step with the following:

`accelerate launch --multi_gpu --num_machines 1  --num_processes 4 rl_training.py --log_with=wandb --model_name=/home/vishal/stack_llama/llama-se-model --reward_model_name=/home/vishal/stack_llama/llama-se-rm --adafactor=False --tokenizer_name=/home/vishal/models/llama_hf --save_freq=100 --output_max_length=128 --batch_size=8 --gradient_accumulation_steps=8 --batched_gen=True --ppo_epochs=4 --seed=0 --learning_rate=1.4e-5 --early_stopping=True --output_dir=llama-se-rl-finetune-128-8-8-1.4e-5_adam`

I'm running into the following issue:
```
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [96,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [96,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [96,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [96,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [96,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/vishal/stack_llama/rl_training.py", line 241, in <module>
    response_tensors = ppo_trainer.generate(
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py", line 414, in generate
    return self._generate_batched(
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py", line 470, in _generate_batched
    generations = self.accelerator.unwrap_model(self.model).generate(**padded_inputs, **generation_kwargs)
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/trl/models/modeling_value_head.py", line 195, in generate
    return self.pretrained_model.generate(*args, **kwargs)
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/peft/peft_model.py", line 721, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/transformers/generation/utils.py", line 1558, in generate
    return self.sample(
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/transformers/generation/utils.py", line 2605, in sample
    outputs = self(
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 537, in forward
    attention_mask = self._prepare_decoder_attention_mask(
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 465, in _prepare_decoder_attention_mask
    combined_attention_mask = _make_causal_mask(
  File "/home/vishal/llama-env-39/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 49, in _make_causal_mask
    mask = torch.full((tgt_len, tgt_len), torch.tensor(torch.finfo(dtype).min, device=device), device=device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

One thing that may be of issue is that I had to change [merge_peft_adapter.py L53-61](https://github.com/lvwerra/trl/blob/main/examples/stack_llama/scripts/merge_peft_adapter.py#L53-L61) and replace it with:
```
model = model.merge_and_unload()
```

**Comment by younesbelkada** [comment]
Hi @vshah505 
Thanks for the issue, that might be a bug in the RL fine-tuning script
Could you try to run just a single training step in that script on CPU to better debug this? `CUDA_VISIBLE_DEVICES= accelerate launch rl_training.py`
Usually when I get CUDA device side assert errors I try to run that script on CPU and try to understand the error trace.
Also the RL finetuning script will be refactored after https://github.com/lvwerra/trl/pull/303 being merged. So I will let you know if I face into the same issue

**Comment by vshah505** [comment]
Thank you! Based on a suggestion, it looks like there was an issue related to the tokenizer. The issue was resolved by installing the transformers from the latest commit and replacing the `AutoTokenizer` with `LlamaTokenizer`

**Comment by teticio** [comment]
@younesbelkada It seems like quite a few people are running into this problem (myself included). Any reason not to make the change suggested by @vshah505 to the code base? Thanks
