### ISSUE TITLE
Deepspeed doesnt like bfloat16 for Reward Model?

### ISSUE THREAD

**Issue by kungfu-eric** [lvwerra/trl#427]
If I don't use deepspeed it's OOM on a 48GB GPU batch size 1 for 7Bn Alpaca model. If I try to use deepspeed, it throws this:
```
_   355 _   _   elif self.r > 0 and not self.merged:                                               _
_   356 _   _   _   result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.   _
_   357 _   _   _   if self.r > 0:                                                                 _
_ _ 358 _   _   _   _   result += self.lora_B(self.lora_A(self.lora_dropout(x))) * self.scaling    _
_   359 _   _   _   return result                                                                  _
_   360 _   _   else:                                                                              _
_   361 _   _   _   return F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bi   _
_                                                                                                  _
_ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            _
_                                                                                                  _
_   1498 _   _   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   _
_   1499 _   _   _   _   or _global_backward_pre_hooks or _global_backward_hooks                   _
_   1500 _   _   _   _   or _global_forward_hooks or _global_forward_pre_hooks):                   _
_ _ 1501 _   _   _   return forward_call(*args, **kwargs)                                          _
_   1502 _   _   # Do not call functions when jit is used                                          _
_   1503 _   _   full_backward_hooks, non_full_backward_hooks = [], []                             _
_   1504 _   _   backward_pre_hooks = []                                                           _
_                                                                                                  _
_ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/linear.py:114 in forward                _
_                                                                                                  _
_   111 _   _   _   init.uniform_(self.bias, -bound, bound)                                        _
_   112 _                                                                                          _
_   113 _   def forward(self, input: Tensor) -> Tensor:                                            _
_ _ 114 _   _   return F.linear(input, self.weight, self.bias)                                     _
_   115 _                                                                                          _
_   116 _   def extra_repr(self) -> str:                                                           _
_   117 _   _   return 'in_features={}, out_features={}, bias={}'.format(                          _
____________________________________________________________________________________________________
RuntimeError: expected scalar type BFloat16 but found Float
```

If using deepspeed and no bfloat16, again OOM... Surely 2x48GB should be enough for a 7Bn param model?

**Comment by younesbelkada** [comment]
Hi @kungfu-eric 
Thanks for the issue, what is the PEFT version you are using?

**Comment by kungfu-eric** [comment]
'0.3.0.dev0'

Adding bf16 to the deepspeed config fixes the bf16 error, but it's still OOM:
```
_ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            _
_                                                                                                  _
_   1498 _   _   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   _
_   1499 _   _   _   _   or _global_backward_pre_hooks or _global_backward_hooks                   _
_   1500 _   _   _   _   or _global_forward_hooks or _global_forward_pre_hooks):                   _
_ _ 1501 _   _   _   return forward_call(*args, **kwargs)                                          _
_   1502 _   _   # Do not call functions when jit is used                                          _
_   1503 _   _   full_backward_hooks, non_full_backward_hooks = [], []                             _
_   1504 _   _   backward_pre_hooks = []                                                           _
_                                                                                                  _
_ /opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:231 in       _
_ forward                                                                                          _
_                                                                                                  _
_   228 _   _   _   attn_weights = torch.max(attn_weights, torch.tensor(torch.finfo(attn_weights   _
_   229 _   _                                                                                      _
_   230 _   _   # upcast attention to fp32                                                         _
_ _ 231 _   _   attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).   _
_   232 _   _   attn_output = torch.matmul(attn_weights, value_states)                             _
_   233 _   _                                                                                      _
_   234 _   _   if attn_output.size() != (bsz, self.num_heads, q_len, self.head_dim):              _
_                                                                                                  _
_ /opt/conda/lib/python3.10/site-packages/torch/nn/functional.py:1845 in softmax                   _
_                                                                                                  _
_   1842 _   if dtype is None:                                                                     _
_   1843 _   _   ret = input.softmax(dim)                                                          _
_   1844 _   else:                                                                                 _
_ _ 1845 _   _   ret = input.softmax(dim, dtype=dtype)                                             _
_   1846 _   return ret                                                                            _
_   1847                                                                                           _
_   1848                                                                                           _
____________________________________________________________________________________________________
OutOfMemoryError: CUDA out of memory. Tried to allocate 22.67 GiB (GPU 0; 47.54 GiB total capacity; 36.17 GiB already allocated; 9.53 GiB free; 36.83 GiB reserved in 
total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and 
PYTORCH_CUDA_ALLOC_CONF
```

**Comment by kungfu-eric** [comment]
Closing this as bfloat16 issue is resolved by adding to deepspeed config. This appears to be an memory issue which can quickly grow out of hand by seq len.
